ENG-8175 check if started and exit start() if so. fix unit tests
Neuro-ID/neuroid-android-sdk pull request #332
Opened 2024-06-24 21:54 UTC by kishisaka-nid

Check if the SDK is already started(). If so, exit immediately. This will stop the starting of multiple data manager queues that might be occurring right now if start() is called twice in a row without stopping.

2024-06-25 20:15 UTC, kevinsites approved these changes

2024-06-25 20:15 UTC, kevinsites requested changes
Can we add a test to verify this result?

2024-06-25 20:49 UTC, kishisaka-nid commented
yeah good idea. will add a startAlreadyStarted() test.

2024-06-25 21:36 UTC, cometman submitted a review, later dismissed

2024-06-26 18:45 UTC, kevinsites approved these changes

2024-06-27 16:02 UTC, cometman approved these changes

2024-06-27 16:09 UTC, merged